package net.projecteuler.solution;

import static net.projecteuler.util.ProblemUtil.isEven;

public class Problem002 implements Problem {

	@Override
	public String getName() {
		return "Even Fibonacci numbers.";
	}

	@Override
	public String getDescription() {
		StringBuilder description = new StringBuilder();
		description.append("Each new term in the Fibonacci sequence is generated by adding the previous two terms. \n");
		description.append("By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... \n");
		description.append("By considering the terms in the Fibonacci sequence whose values do not exceed four million, \n");
		description.append("find the sum of the even-valued terms.");
		
		return description.toString();
	}

	@Override
	public long solve() {
		int actual = 1;
		int prev = 0;
		int sum = 0;
		
		do {
			int aux = actual;
			actual = actual + prev;
			prev = aux;
			
			if (isEven(actual)) {
				sum += actual;
			}
			
		} while ((actual + prev) < 4000000);
		
		return sum;
	}
}