package net.projecteuler.solution;

/**
 * Even Fibonacci numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */
public class Problem002 {
	
	public static void main(String[] args) {
		System.out.println(calculate());
	}

	private static int calculate() {

		int actual = 1;
		int prev = 0;
		int sum = 0;
		int limit = 4000000;
		
		do {
			int aux = actual;
			actual = actual + prev;
			prev = aux;
			
			if (actual % 2 == 0) {
				sum += actual;
			}
			
		} while (actual + prev < limit);
		
		return sum;
	}
}